server:
  port: 8083

spring:
  application:
    name: ecommerce-order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/ecommerce_order?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root
  cloud:
    function:
      definition: orderMqConsumer;paySuccessConsumer;orderDelayConsumer
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: public
      config:
        import-check:
          enabled: false
    stream:
      rocketmq:
        binder:
          name-server: localhost:9876
      bindings:
        orderMqConsumer-in-0:
          destination: seckill-order
          group: order-consumer-group
          content-type: application/json
          consumer:
            concurrency: 1
        paySuccessConsumer-in-0:
          destination: pay-success
          group: order-pay-consumer-group
          content-type: application/json
          consumer:
            concurrency: 1
        orderDelayConsumer-in-0:
          destination: order-delay
          group: order-delay-consumer-group
          content-type: application/json
          consumer:
            concurrency: 1
        orderNotifyConsumer-in-0:
          destination: order-notify
          group: email-notify-consumer-group
          content-type: application/json
        orderDelay-out-0:
          destination: order-delay
          content-type: application/json
        stockRollback-out-0:
          destination: stock-rollback
          content-type: application/json
        orderNotify-out-0:
          destination: order-notify
          content-type: application/json

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.xinyu.ecommerce.order.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.xinyu.ecommerce: debug
