server:
  port: 8080

spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive
  config:
    import: optional:nacos:${spring.cloud.nacos.server-addr}
  cloud:
    nacos:
      server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  data:
    redis:
      host: localhost
      port: 6379

dubbo:
  registry:
    address: nacos://localhost:8848
  protocol:
    name: dubbo
    port: 20880

management:
  endpoints:
    web:
      exposure:
        include: "*"
