spring:
  application:
    name: ecommerce-gateway
  main:
    web-application-type: reactive
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: public
      config:
        import-check:
          enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://ecommerce-user
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=1
        - id: store-service
          uri: lb://ecommerce-store
          predicates:
            - Path=/api/store/**
          filters:
            - StripPrefix=1
        - id: order-service
          uri: lb://ecommerce-order
          predicates:
            - Path=/api/order/**
          filters:
            - StripPrefix=1
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600

server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: debug
