server:
  port: 8081

spring:
  application:
    name: ecommerce-store
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/ecommerce_store?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root
    hikari:
      connection-character-encoding: UTF-8
  cloud:
    function:
      definition: stockRollbackConsumer;payConfirmedConsumer
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: public
      config:
        import-check:
          enabled: false
    stream:
      rocketmq:
        binder:
          name-server: localhost:9876
      bindings:
        seckill-order-out-0:
          destination: seckill-order
          content-type: application/json
        stockRollbackConsumer-in-0:
          destination: stock-rollback
          group: store-rollback-consumer-group
          content-type: application/json
          consumer:
            concurrency: 1
        payConfirmedConsumer-in-0:
          destination: pay-confirmed
          group: store-pay-consumer-group
          content-type: application/json
          consumer:
            concurrency: 1
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 3000ms

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.xinyu.ecommerce.store.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.xinyu.ecommerce: debug
