server:
  port: 8084

spring:
  application:
    name: email-service
  config:
    import: optional:nacos:${spring.cloud.nacos.server-addr}
  cloud:
    nacos:
      server-addr: localhost:8848
      config:
        import-check:
          enabled: false

dubbo:
  registry:
    address: nacos://localhost:8848
  protocol:
    name: dubbo
    port: 20884

rocketmq:
  name-server: localhost:9876
  consumer:
    group: email-consumer-group

management:
  endpoints:
    web:
      exposure:
        include: "*"
