server:
  port: 8084

spring:
  application:
    name: email-service
  config:
    import: optional:nacos:${spring.cloud.nacos.server-addr}
  cloud:
    nacos:
      server-addr: localhost:8848
      config:
        import-check:
          enabled: false
    stream:
      function:
        definition: orderNotifyConsumer
      rocketmq:
        binder:
          name-server: localhost:9876
        bindings:
          orderNotifyConsumer-in-0:
            consumer:
              group: email-notify-consumer-group
              topic: order-notify
      bindings:
        orderNotifyConsumer-in-0:
          destination: order-notify
          content-type: application/json
          consumer:
            concurrency: 1

dubbo:
  registry:
    address: nacos://localhost:8848
  protocol:
    name: dubbo
    port: 20884

management:
  endpoints:
    web:
      exposure:
        include: "*"
