server:
  port: 8084

spring:
  application:
    name: pay-service
  config:
    import: optional:nacos:${spring.cloud.nacos.server-addr}
  cloud:
    nacos:
      server-addr: localhost:8848
      config:
        import-check:
          enabled: false
    stream:
      rocketmq:
        binder:
          name-server: localhost:9876
      bindings:
        paySuccess-out-0:
          destination: pay-success
          content-type: application/json
  datasource:
    url: jdbc:mysql://localhost:3307/ecommerce_pay?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root

dubbo:
  registry:
    address: nacos://localhost:8848
  protocol:
    name: dubbo
    port: 20883

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto

management:
  endpoints:
    web:
      exposure:
        include: "*"
